version: doc"3"

services:
  api-covidstat:
    build: .
    # specifying the image-name for the image built using dockerfile
    image: "covidstat:0.0.1"
    container_name: "covidstat_service"
    networks:
      - casestudy
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}

networks:
  casestudy:
    external: true