# in minutes
cache:
  ttl:
    latestStatCountry: 35
    oneDayPrevious: 1440
    twoDayPrevious: 2880
    vaccineCoverageTrends: 7200
    alertMessage: 35

  host: localhost
  port: 6379

api:
  key: 3f5c6d0e-9f48-4d5c-ae78-2db63e2f8c41

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers

  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

