# in minutes
cache:
  ttl:
    latestStatCountry: 35
    oneDayPrevious: 1440
    twoDayPrevious: 2880
    vaccineCoverageTrends: 7200
    alertMessage: 35

  host: localhost
  port: 6379

api:
  key: 3f5c6d0e-9f48-4d5c-ae78-2db63e2f8c41

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers

otel:
  service:
    name: covidstat-service

  traces:
    exporter: otlp

  exporter:
    otlp:
      endpoint: http://otel-collector:4317

  instrumentation:
    logback-mdc:
      enabled: true

  metrics:
    exporter: none
  logs:
    exporter: none