package com.myreflectionthoughts.covidstat.constant;

public enum Country {

        AFGHANISTAN("Afghanistan"),
        ALBANIA("Albania"),
        ALGERIA("Algeria"),
        ANDORRA("Andorra"),
        ANGOLA("Angola"),
        ANTARCTICA("Antarctica"),
        ANTIGUA_AND_BARBUDA("Antigua and Barbuda"),
        ARGENTINA("Argentina"),
        ARMENIA("Armenia"),
        AUSTRALIA("Australia"),
        AUSTRIA("Austria"),
        AZERBAIJAN("Azerbaijan"),
        BAHAMAS("Bahamas"),
        BAHRAIN("Bahrain"),
        BANGLADESH("Bangladesh"),
        BARBADOS("Barbados"),
        BELARUS("Belarus"),
        BELGIUM("Belgium"),
        BELIZE("Belize"),
        BENIN("Benin"),
        BHUTAN("Bhutan"),
        BOLIVIA("Bolivia"),
        BOSNIA("Bosnia"),
        BOTSWANA("Botswana"),
        BRAZIL("Brazil"),
        BRUNEI("Brunei"),
        BULGARIA("Bulgaria"),
        BURKINA_FASO("Burkina Faso"),
        BURMA("Burma"),
        BURUNDI("Burundi"),
        CABO_VERDE("Cabo Verde"),
        CAMBODIA("Cambodia"),
        CAMEROON("Cameroon"),
        CANADA("Canada"),
        CENTRAL_AFRICAN_REPUBLIC("Central African Republic"),
        CHAD("Chad"),
        CHILE("Chile"),
        CHINA("China"),
        COLOMBIA("Colombia"),
        COMOROS("Comoros"),
        CONGO("Congo"),
        COSTA_RICA("Costa Rica"),
        COTE_D_IVOIRE("Côte d'Ivoire"),
        CROATIA("Croatia"),
        CUBA("Cuba"),
        CYPRUS("Cyprus"),
        CZECHIA("Czechia"),
        DENMARK("Denmark"),
        DIAMOND_PRINCESS("Diamond Princess"),
        DJIBOUTI("Djibouti"),
        DOMINICA("Dominica"),
        DOMINICAN_REPUBLIC("Dominican Republic"),
        DRC("DRC"),
        ECUADOR("Ecuador"),
        EGYPT("Egypt"),
        EL_SALVADOR("El Salvador"),
        EQUATORIAL_GUINEA("Equatorial Guinea"),
        ERITREA("Eritrea"),
        ESTONIA("Estonia"),
        ETHIOPIA("Ethiopia"),
        FIJI("Fiji"),
        FINLAND("Finland"),
        FRANCE("France"),
        GABON("Gabon"),
        GAMBIA("Gambia"),
        GEORGIA("Georgia"),
        GERMANY("Germany"),
        GHANA("Ghana"),
        GREECE("Greece"),
        GRENADA("Grenada"),
        GUATEMALA("Guatemala"),
        GUINEA_BISSAU("Guinea-Bissau"),
        GUINEA("Guinea"),
        GUYANA("Guyana"),
        HAITI("Haiti"),
        HOLY_SEE("Holy See"),
        HONDURAS("Honduras"),
        HUNGARY("Hungary"),
        ICELAND("Iceland"),
        INDIA("India"),
        INDONESIA("Indonesia"),
        IRAN("Iran"),
        IRAQ("Iraq"),
        IRELAND("Ireland"),
        ISRAEL("Israel"),
        ITALY("Italy"),
        JAMAICA("Jamaica"),
        JAPAN("Japan"),
        JORDAN("Jordan"),
        KAZAKHSTAN("Kazakhstan"),
        KENYA("Kenya"),
        KIRIBATI("Kiribati"),
        KOSOVO("Kosovo"),
        KUWAIT("Kuwait"),
        KYRGYZSTAN("Kyrgyzstan"),
        LAO_PDR("Lao People's Democratic Republic"),
        LATVIA("Latvia"),
        LEBANON("Lebanon"),
        LESOTHO("Lesotho"),
        LIBERIA("Liberia"),
        LIBYA("Libyan Arab Jamahiriya"),
        LIECHTENSTEIN("Liechtenstein"),
        LITHUANIA("Lithuania"),
        LUXEMBOURG("Luxembourg"),
        MACEDONIA("Macedonia"),
        MADAGASCAR("Madagascar"),
        MALAWI("Malawi"),
        MALAYSIA("Malaysia"),
        MALDIVES("Maldives"),
        MALI("Mali"),
        MALTA("Malta"),
        MARSHALL_ISLANDS("Marshall Islands"),
        MAURITANIA("Mauritania"),
        MAURITIUS("Mauritius"),
        MEXICO("Mexico"),
        MICRONESIA("Micronesia"),
        MOLDOVA("Moldova"),
        MONACO("Monaco"),
        MONGOLIA("Mongolia"),
        MONTENEGRO("Montenegro"),
        MOROCCO("Morocco"),
        MOZAMBIQUE("Mozambique"),
        MS_ZAANDAM("MS Zaandam"),
        NORTH_KOREA("N. Korea"),
        NAMIBIA("Namibia"),
        NAURU("Nauru"),
        NEPAL("Nepal"),
        NETHERLANDS("Netherlands"),
        NEW_ZEALAND("New Zealand"),
        NICARAGUA("Nicaragua"),
        NIGER("Niger"),
        NIGERIA("Nigeria"),
        NORWAY("Norway"),
        OMAN("Oman"),
        PAKISTAN("Pakistan"),
        PALAU("Palau"),
        PANAMA("Panama"),
        PAPUA_NEW_GUINEA("Papua New Guinea"),
        PARAGUAY("Paraguay"),
        PERU("Peru"),
        PHILIPPINES("Philippines"),
        POLAND("Poland"),
        PORTUGAL("Portugal"),
        QATAR("Qatar"),
        ROMANIA("Romania"),
        RUSSIA("Russia"),
        RWANDA("Rwanda"),
        SOUTH_KOREA("S. Korea"),
        SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis"),
        SAINT_LUCIA("Saint Lucia"),
        SAINT_VINCENT_AND_GRENADINES("Saint Vincent and the Grenadines"),
        SAMOA("Samoa"),
        SAN_MARINO("San Marino"),
        SAO_TOME_AND_PRINCIPE("Sao Tome and Principe"),
        SAUDI_ARABIA("Saudi Arabia"),
        SENEGAL("Senegal"),
        SERBIA("Serbia"),
        SEYCHELLES("Seychelles"),
        SIERRA_LEONE("Sierra Leone"),
        SINGAPORE("Singapore"),
        SLOVAKIA("Slovakia"),
        SLOVENIA("Slovenia"),
        SOLOMON_ISLANDS("Solomon Islands"),
        SOMALIA("Somalia"),
        SOUTH_AFRICA("South Africa"),
        SOUTH_SUDAN("South Sudan"),
        SPAIN("Spain"),
        SRI_LANKA("Sri Lanka"),
        SUDAN("Sudan"),
        SUMMER_OLYMPICS_2020("Summer Olympics 2020"),
        SURINAME("Suriname"),
        SWAZILAND("Swaziland"),
        SWEDEN("Sweden"),
        SWITZERLAND("Switzerland"),
        SYRIA("Syrian Arab Republic"),
        TAIWAN("Taiwan"),
        TAJIKISTAN("Tajikistan"),
        TANZANIA("Tanzania"),
        THAILAND("Thailand"),
        TIMOR_LESTE("Timor-Leste"),
        TOGO("Togo"),
        TONGA("Tonga"),
        TRINIDAD_AND_TOBAGO("Trinidad and Tobago"),
        TUNISIA("Tunisia"),
        TURKEY("Turkey"),
        TUVALU("Tuvalu"),
        UAE("UAE"),
        UGANDA("Uganda"),
        UK("UK"),
        UKRAINE("Ukraine"),
        URUGUAY("Uruguay"),
        USA("USA"),
        UZBEKISTAN("Uzbekistan"),
        VANUATU("Vanuatu"),
        VENEZUELA("Venezuela"),
        VIETNAM("Vietnam"),
        WEST_BANK_AND_GAZA("West Bank and Gaza"),
        WINTER_OLYMPICS_2022("Winter Olympics 2022"),
        YEMEN("Yemen"),
        ZAMBIA("Zambia"),
        ZIMBABWE("Zimbabwe");

        private final String displayName;

        Country(String displayName) {
            this.displayName = displayName;
        }

        public String getDisplayName() {
            return displayName;
        }
}

