apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  labels:
    group: cache
spec:
  selector:
    matchLabels:
      app: redis-cache
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-cache
        group: cache
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
