apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
  labels:
    group: cache
spec:
  selector:
      app: redis-cache # this tells that the app:redis-cache are behind this load-balancer
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379